const talents = [
		"Force", 
		"Dexterity", 
		"Quickness", 
		"Toughness", 
		"Moxy", 
		"Intelligence", 
		"Perception", 
		"Grit", 
	];
const skills = [
		"Melee Combat", 
		"Projectile Weapons", 
		"Firearms", 
		"Warfare", 
		"Athletics", 
		"Tenacity", 
		"Stealth", 
		"Investigation", 
		"Conveyance",
		"Survival", 
		"Tradesman", 
		"Deception", 
		"Inspiration", 
		"Intimidation", 
		"Influence", 
		"Academia", 
		"Medical", 
		"Esoterics", 
		"Attunement", 
	];
